[build]
dist = "../static/play"
index = "./index.html"
public_url = "/play/"

[[proxy]]
rewrite = "/play/create-gist"
backend = "http://localhost:8787/play/create-gist"

[[hooks]]
# Embed the header in the playground's index.html
stage = "post_build"
command = "sh"
command_arguments = [
  "-c",
  "cargo run --release --manifest-path ../tools/postprocess-playground/Cargo.toml -- $TRUNK_STAGING_DIR",
]
